title: HuiChing Heng # your name (or website title) here
logo: "/images/avatar.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <strong>About me</strong><br>
  With years experience in the digital design industry. Further develop into data analysis. Look forward to contributing to an organization to exercise and develop my skills. 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/huichingheng/">View My LinkedIn Profile</a>
  <br>
  <a href="https://www.behance.net/huichingheng">View My Behance page</a>
 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
